name: eldercare_ai
description: "ElderCare AI - Smart elder care companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0

  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  image_picker: ^1.0.4
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  another_telephony: ^0.4.0
  sensors_plus: ^6.1.1
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
